Code example
byubrg/FDA-Sampling pull request #3
Opened 2018-09-29 00:07 UTC by MSBradshaw

Created a python module for housing functions for interacting with scikit-learn models. Also added a main script for actually running analysis.

2018-09-29 03:45 UTC, jdayton3 requested changes
Looks great! I think this will be super helpful for getting people oriented with scikit-learn. 

A few general comments:

* Can we document how to use these files, either in the `README.md` or in a `CONTRIBUTING.md`?
* It might be nice to have some pre-merge linting checks for PEP8 compliance, especially once we have ~10 different people committing code. Spyder also makes it easy to check that stuff (at least on Ubuntu, you just have to hit `F8` and it runs pylint on the current file). (This would probably be a separate pull request getting it set up.)
* ~~Should we make subdirectories for modules / packages, scripts, and data? It might make the repo a little more organized.~~ Edit: I did this in #4

2018-09-29 03:45 UTC, jdayton3 commented on main.py
> +import Learner_Functions as fl
Why `fl` instead of `lf`?

2018-09-29 03:45 UTC, jdayton3 commented on Learner_Functions.py
> +"""
[PEP8 says](https://www.python.org/dev/peps/pep-0008/?#package-and-module-names) module names should be all lowercase.

2018-09-29 03:45 UTC, jdayton3 commented on Learner_Functions.py
> +
What's this empty docstring?

2018-09-29 03:45 UTC, jdayton3 commented on main.py
> +#remove the sample labels and transform the data such that protiens are features
"protien" -> "protein" :slightly_smiling_face:

2018-09-29 03:45 UTC, jdayton3 commented on main.py
> +import Learner_Functions as fl
I get a couple of `DataConversionWarning`s when I run this file with Python 3:

```
/home/jdayton3/miniconda3/envs/py36/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
...
```

^ Repeated 10x.

2018-09-29 03:45 UTC, jdayton3 commented on main.py
> +import Learner_Functions as fl
Would it make sense to remove this file and put the code in a `if __name__ == "__main__":` block in `Learner_Functions.py` instead?

2018-10-03 22:31 UTC, MSBradshaw commented
Fixed spelling mistakes
added to the read me
added a missing column name to train_pro.tsv

2018-10-03 22:42 UTC, jdayton3 approved these changes

2018-10-03 23:17 UTC, merged