Soft voting
byubrg/FDA-Sampling pull request #32
Opened 2018-10-30 19:22 UTC by ercsuh

Used VotingClassifier class from sklearn to make soft vote predictions.
Also, trained all learners for gender and msi on main.py.

2018-10-30 22:21 UTC, MSBradshaw requested changes

2018-10-30 22:21 UTC, MSBradshaw commented on main.py
> +print("\n\n******************************************************************\n)
this string does not end, it is a syntax error

2018-10-30 22:21 UTC, MSBradshaw commented on main.py
> +print("\n\n******************************************************************\n)
syntax error

2018-10-31 01:21 UTC, ricsuh commented on main.py
> +print("\n\n******************************************************************\n)
1. Fixed syntax error. 
2. SGD: Apparently, probability estimates aren't available for hinge loss, which is SGD's default loss function. So I made a separate, modified function in learner_functions that changes the parameter in SGDClassifier() from `loss='hinge'` to `loss='modified_huber'`. This new loss function allows probability estimates.
3. NC: I removed Nearest Centroid from the list of learners because it doesn't predict probabilities, so it can't be used for soft voting (at least from what I've read on the internet...).

2018-10-31 04:15 UTC, MSBradshaw approved these changes

2018-10-31 04:57 UTC, merged